
server.port: 8706

spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  r2dbc:
    url: r2dbc:mysql://localhost:3306/order
    username: root
    password: root
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  flyway:
    url: jdbc:mysql://localhost:3306/order
    user: root
    password: root
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    locations: classpath:db/migration
  jpa:
    properties.hibernate:
      hbm2ddl.auto: ""
      dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true